services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - .:/go_project
      - db-data:/var/lib/postgresql/data
      - ./internal/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - go-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    stop_grace_period: 5s
    env_file:
      - .env # Loads environment variables from .env file
    networks:
      - go-network
    environment:
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_NAME: golang_project_db
      DB_HOST: db
    command: ["/usr/local/bin/go_project", "--port", "8080"] # Passes port flag explicitly

networks:
  go-network:
    driver: bridge

volumes:
  db-data:
